## Statistics for Data Science 

### Sample theory

* Bir popülasyon içerisinden bir alt küme seçme işlemine örneklem denir.
* Birden fazla örneklem üzerinden baktığımızda ise bu duruma örneklem dağılımı denir.

10.000 kişi içerisinden 100 kişi seçerek onların yaş ortalamasını bulacağız.

In [1]:
import numpy as np
population = np.random.randint(0, 80, 10000)
population

array([64, 31, 70, ..., 73, 76, 45])

In [2]:
population[0:10]

array([64, 31, 70,  7, 31, 64,  1, 35, 46, 44])

### Getting sample

In [3]:
np.random.seed(10) #Aynı örneklemi çekmek için
sample = np.random.choice(a = population, size = 100)
sample

array([40, 69, 60, 44, 50, 20, 13, 17, 41, 72, 17, 16, 29, 15, 70, 75, 10,
       22, 49, 65,  4, 43,  9, 35, 32, 23,  6, 70, 31, 38, 36,  7,  6, 76,
       23, 44, 56, 13, 19, 41, 75, 17, 49, 78, 12, 29, 45,  1, 13, 41, 28,
       16, 60, 15, 49, 74, 32, 34, 25, 54, 31, 58, 72,  3,  1, 49,  9, 56,
       41, 70, 25, 32, 59, 38, 26,  5, 30, 58, 73, 16, 21, 72, 66,  0, 10,
       72, 45, 21, 57, 28, 79, 24, 65, 33, 46,  9, 62, 37, 23, 68])

In [4]:
sample.mean()

37.43

In [5]:
population.mean()

39.6943

In [6]:
np.random.seed(10)
sample1  = np.random.choice(a = population, size = 100)
sample2  = np.random.choice(a = population, size = 100)
sample3  = np.random.choice(a = population, size = 100)
sample4  = np.random.choice(a = population, size = 100)
sample5  = np.random.choice(a = population, size = 100)
sample6  = np.random.choice(a = population, size = 100)
sample7  = np.random.choice(a = population, size = 100)
sample8  = np.random.choice(a = population, size = 100)
sample9  = np.random.choice(a = population, size = 100)
sample10 = np.random.choice(a = population, size = 100)

In [7]:
(sample1.mean() +
sample2.mean() +
sample3.mean() +
sample4.mean() +
sample5.mean() +
sample6.mean() +
sample7.mean() +
sample8.mean() +
sample9.mean() +
sample10.mean()) / 10

39.016

### Descriptive Statistics

* varyans = ortalama etrafındaki dağılımın ölçümü
* cov(X, Y) = E[(X - E[X])](Y - E[Y])] : 2 değişken arasındaki ilişkiyi incelemek için. (İlişkinin değişkenliği)
* Kolerasyon : İki değişken arasındaki ilişkinin anlamı olup olmadığını. 

In [9]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [13]:
!pip install researchpy
import researchpy as rp

In [15]:
rp.summary_cont(df[["total_bill", "tip", "size"]])

Variable      N       Mean        SD        SE  95% Conf.   Interval
0  total_bill  244.0  19.785943  8.902412  0.569919  18.663332  20.908554
1         tip  244.0   2.998279  1.383638  0.088578   2.823799   3.172758
2        size  244.0   2.569672  0.951100  0.060888   2.449737   2.689608

In [17]:
rp.summary_cat(df[["sex", "smoker", "day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [18]:
df[["tip", "total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [20]:
df[["tip", "total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000